### PR TITLE
Fix modular jar final permissions

### LINKED ISSUE #332: Modular Jar file permissions changed when fixing modification time
When a new modular jar file is generated with `maven-jar-plugin` with Java 11, the final permissions of the file are restricted to the current user instead of using the environment umask which usually allows for group and other users to access the file as well.

This is caused by the use of `Files#createTempFile()` which has a restrictive file permission model for security reason but as the temporary file is generated next to the original jar file, and there's no sensitive reason to restrict its access, the restrictive file permission should not be needed

### PR DESCRIPTION
**Pull request by laurentgo**
When a new modular jar file is generated with maven-jar-plugin with Java 11, the final permissions of the file are restricted to the current user instead of using the environment umask which usually allows for group and other users to access the file as well.

This is caused by the use of Files#createTempFile() which has a restrictive file permission model for security reason but as the temporary file is generated next to the original jar file, and there's no sensitive reason to restrict its access, the restrictive file permission should not be needed.

Fix the issue by creating a simple temporary file generator method.

Fixes #332

### CODE REVIEW

**Comment by plamentotev** [comment]
Hi,

Thanks for the contribution. `createTempFile` accepts array of `FileAttribute`. I wonder if we can use it to create temp file with the same permissions as the original file.

**Comment by plamentotev** [comment]
Also I noticed that the temp file is not marked for deletion. So if the move operation fails the temp file will be left on the filesystem.

**Comment by laurentgo** [comment]
> Thanks for the contribution. `createTempFile` accepts array of `FileAttribute`. I wonder if we can use it to create temp file with the same permissions as the original file.

Yes, it is possible but as the other tools uses the default umask, I thought this was not needed. Do you want me to implement this behavior though?

> Also I noticed that the temp file is not marked for deletion. So if the move operation fails the temp file will be left on the filesystem.

As far as I can tell from the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile-java.nio.file.Path-java.lang.String-java.lang.String-java.nio.file.attribute.FileAttribute...-), `Files.createTempFile(...)` does not mark the file for deletion either, so it is also an issue with the existing code. Do we want to address it in this change as well?

**Comment by plamentotev** [comment]
> > Thanks for the contribution. `createTempFile` accepts array of `FileAttribute`. I wonder if we can use it to create temp file with the same permissions as the original file.
> 
> Yes, it is possible but as the other tools uses the default umask, I thought this was not needed. Do you want me to implement this behavior though?

I'm not sure I follow which tools you have in mind. In this case it seems more robust to use explicitly the same permissions as the original file as this is the intended behavior if my understanding is correct. 

> > Also I noticed that the temp file is not marked for deletion. So if the move operation fails the temp file will be left on the filesystem.
> 
> As far as I can tell from the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile-java.nio.file.Path-java.lang.String-java.lang.String-java.nio.file.attribute.FileAttribute...-), `Files.createTempFile(...)` does not mark the file for deletion either, so it is also an issue with the existing code. Do we want to address it in this change as well?

Yes, this is the existing behavior. If you want and think it makes sense would be great if you can add this change as well.

**Comment by laurentgo** [comment]
> > > Thanks for the contribution. `createTempFile` accepts array of `FileAttribute`. I wonder if we can use it to create temp file with the same permissions as the original file.
> > 
> > 
> > Yes, it is possible but as the other tools uses the default umask, I thought this was not needed. Do you want me to implement this behavior though?
> 
> I'm not sure I follow which tools you have in mind. In this case it seems more robust to use explicitly the same permissions as the original file as this is the intended behavior if my understanding is correct.
> 

I was referring to `jar` tool or `java` (when using `Files#createNewFile()`

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java [hunk 1]
```diff
@@ -147,23 +155,42 @@ protected void postCreateArchive() throws ArchiverException {
...
-            while (entries.hasMoreElements()) {
-                ZipEntry entry = entries.nextElement();
-                // Not using setLastModifiedTime(FileTime) as it sets the extended timestamp
-                // which is not compatible with the jar tool output.
-                entry.setTime(timeMillis);
-                out.putNextEntry(entry);
-                if (!entry.isDirectory()) {
-                    IOUtil.copy(zipFile.getInputStream(entry), out);
+        FileAttribute<?>[] attributes;
+        if (IS_POSIX) {
```
Comment (plamentotev) [inline src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java:159]: If `PosixFileAttributeView` is not available for some reason, `getFileAttributeView` would return `null`q so we can use that to check instead of the default file system.

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java [hunk 2]
```diff
@@ -147,23 +155,42 @@ protected void postCreateArchive() throws ArchiverException {
...
+            PosixFileAttributes posixFileAttributes = Files.getFileAttributeView(destFile, PosixFileAttributeView.class)
+                    .readAttributes();
```
Comment (plamentotev) [inline src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java:161]: The call of `.readAttributes()` here may throw NPE, as `getFileAttributeView` may return `null`.

Also by default that would follow symbolic links. I am just thinking out loud if we should set the `NOFOLLOW_LINKS` option should be set. `Files.move` would not follow the link, but rather replace it. Also I don't think this should be symlink. So maybe we can set the flag to be on the safe side?

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java [hunk 3]
```diff
@@ -66,6 +71,9 @@ public class JarToolModularJarArchiver extends ModularJarArchiver {
 
     private static final Pattern MRJAR_VERSION_AREA = Pattern.compile("META-INF/versions/\\d+/");
 
+    private static final boolean IS_POSIX =
```
[the remark this answers is not in the document]
Comment (laurentgo) [reply src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java]: Correct

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java (hunk 1 above)
Comment (laurentgo) [reply src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java]: done

Comment (laurentgo) [reply src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java]: I think this was taken care by the `IS_POSIX` check because `destFile` was a `Path` instance constructed out of a `File` instance using [File#toPath()](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#toPath--) and this would have been using the default filesystem.
But I followed your suggestion and replaced the `IS_POSIX` check with a `null` check.

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java (hunk 2 above)
Comment (laurentgo) [reply src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java]: I think this was taken care by the `IS_POSIX` check because `destFile` was a `Path` instance constructed out of a `File` instance using [File#toPath()](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#toPath--) and this would have been using the default filesystem.
But I followed your suggestion and replaced the `IS_POSIX` check with a `null` check.

File: src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (laurentgo) [reply src/main/java/org/codehaus/plexus/archiver/jar/JarToolModularJarArchiver.java]: Actually it should be guaranteed because of the use of `File#toPath()`
